package org.zhiqiang.lu.maven.plugins.mybatis.generator.plugins;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.*;

import java.util.List;


public class GeneratorSwagger2Doc extends PluginAdapter {
    public boolean validate(List<String> list) {
        return true;
    }

    public static boolean controller_swagger = false;

    @Override
    public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        // 添加entity类注释
        String docLine = "/**\n" +
                " * %s,请勿手工改动此文件,请使用 mybatis generator 插件生成\n" +
                " * \n" +
                " * @author generated by Q's plugin\n" +
                " */";
        docLine = String.format(docLine, introspectedTable.getRemarks());
        topLevelClass.addJavaDocLine(docLine);
        topLevelClass.addAnnotation("@ApiModel(value = \"" + introspectedTable.getRemarks() + "\")");
        topLevelClass.addImportedType("io.swagger.annotations.ApiModel");
        topLevelClass.addImportedType("io.swagger.annotations.ApiModelProperty");
        controller_swagger = true;
        return super.modelBaseRecordClassGenerated(topLevelClass, introspectedTable);
    }

    @Override
    public boolean modelFieldGenerated(Field field, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn, IntrospectedTable introspectedTable, ModelClassType modelClassType) {
        String remmarks = introspectedColumn.getRemarks() != null ? introspectedColumn.getRemarks() : introspectedColumn.getJavaProperty();
        field.addAnnotation("@ApiModelProperty(value = \"[" + introspectedColumn.getLength() + "]" + remmarks + "\")");
        return super.modelFieldGenerated(field, topLevelClass, introspectedColumn, introspectedTable, modelClassType);
    }
}
