package ${javaMapperTargetPackage}.extend;

import ${javaClientTargetPackage}.${EntityName}Mapper;
/**
* @author generated by Q's plugin
*/
public interface ${EntityName}MapperExtend extends ${EntityName}Mapper{

}